export const sample_foods = [
  {
    id: "1",
    name: "Pizza Pepperoni",
    cookTime: "10-20",
    price: 10,
    favourite: false,
    origins: ["Italy"],
    stars: 4.5,
    imageUrl: "food-1.png",
    tags: ["FastFood", "Pizza", "Lunch"],
  },
  {
    id: "2",
    name: "Spaghetti Carbonara",
    cookTime: "15-25",
    price: 12,
    favourite: true,
    origins: ["Italy"],
    stars: 4.7,
    imageUrl: "food-2.jpg",
    tags: ["Pasta", "Italian", "Dinner"],
  },
  {
    id: "3",
    name: "Sushi",
    cookTime: "5-15",
    price: 15,
    favourite: false,
    origins: ["Japan"],
    stars: 4.8,
    imageUrl: "food-3.jpg",
    tags: ["Seafood", "Japanese", "Dinner"],
  },
  {
    id: "4",
    name: "Burger",
    cookTime: "10-15",
    price: 8,
    favourite: true,
    origins: ["USA"],
    stars: 4.2,
    imageUrl: "food-4.jpg",
    tags: ["FastFood", "American", "Lunch"],
  },
  {
    id: "5",
    name: "Tacos",
    cookTime: "5-10",
    price: 7,
    favourite: false,
    origins: ["Mexico"],
    stars: 4.6,
    imageUrl: "food-5.jpg",
    tags: ["Mexican", "Snack", "Lunch"],
  },
  {
    id: "6",
    name: "Pad Thai",
    cookTime: "15-20",
    price: 9,
    favourite: true,
    origins: ["Thailand"],
    stars: 4.5,
    imageUrl: "food-6.jpg",
    tags: ["Thai", "Noodles", "Dinner"],
  },
  {
    id: "7",
    name: "Croissant",
    cookTime: "20-30",
    price: 3,
    favourite: false,
    origins: ["France"],
    stars: 4.3,
    imageUrl: "food-7.jpg",
    tags: ["Breakfast", "Pastry", "French"],
  },
  {
    id: "8",
    name: "Falafel",
    cookTime: "10-15",
    price: 5,
    favourite: true,
    origins: ["Middle East"],
    stars: 4.4,
    imageUrl: "food-8.jpg",
    tags: ["Vegetarian", "MiddleEastern", "Snack"],
  },
  {
    id: "9",
    name: "Peking Duck",
    cookTime: "60-90",
    price: 25,
    favourite: false,
    origins: ["China"],
    stars: 4.9,
    imageUrl: "food-9.jpg",
    tags: ["Chinese", "Gourmet", "Dinner"],
  },
  {
    id: "10",
    name: "Butter Chicken",
    cookTime: "30-40",
    price: 14,
    favourite: true,
    origins: ["India"],
    stars: 4.7,
    imageUrl: "food-10.jpg",
    tags: ["Indian", "Curry", "Dinner"],
  },
  {
    id: "11",
    name: "Fish and Chips",
    cookTime: "20-30",
    price: 10,
    favourite: false,
    origins: ["UK"],
    stars: 4.1,
    imageUrl: "food-11.jpg",
    tags: ["British", "FastFood", "Lunch"],
  },
];

export const sample_tags = [
  { name: "All", count: sample_foods.length },
  {
    name: "FastFood",
    count: sample_foods.filter((food) => food.tags.includes("FastFood")).length,
  },
  {
    name: "Pizza",
    count: sample_foods.filter((food) => food.tags.includes("Pizza")).length,
  },
  {
    name: "Lunch",
    count: sample_foods.filter((food) => food.tags.includes("Lunch")).length,
  },
  {
    name: "Pasta",
    count: sample_foods.filter((food) => food.tags.includes("Pasta")).length,
  },
  {
    name: "Italian",
    count: sample_foods.filter((food) => food.tags.includes("Italian")).length,
  },
  {
    name: "Dinner",
    count: sample_foods.filter((food) => food.tags.includes("Dinner")).length,
  },
];

export const sample_users = [
  {
    id: 1,
    name: "John Doe",
    email: "john@gmail.com",
    password: "12345",
    address: "Toronto",
    isAdmin: false,
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane@gmail.com",
    password: "abcde",
    address: "Vancouver",
    isAdmin: false,
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice@gmail.com",
    password: "qwerty",
    address: "Montreal",
    isAdmin: true,
  },
  {
    id: 4,
    name: "Bob Brown",
    email: "bob@gmail.com",
    password: "password",
    address: "Calgary",
    isAdmin: false,
  },
  {
    id: 5,
    name: "Charlie Davis",
    email: "charlie@gmail.com",
    password: "123abc",
    address: "Ottawa",
    isAdmin: false,
  },
  {
    id: 6,
    name: "David Wilson",
    email: "david@gmail.com",
    password: "david123",
    address: "Edmonton",
    isAdmin: false,
  },
];
